"""init books model

Revision ID: 8918b0a3d03e
Revises: 1c147c22af01
Create Date: 2024-03-01 16:00:31.517871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8918b0a3d03e'
down_revision = '1c147c22af01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_column('super_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('super_user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
